name: Deploy Worker
on:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Build & Deploy Worker
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm i
        uses: cloudflare/wrangler-action@v3
      - run: sed -i s/KV_NAME/${{ secrets.KV_NAME }}/g wrangler.toml
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
